# Generated by Django 5.2.7 on 2025-10-28 14:06

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('photo', models.FileField(upload_to='photos/', validators=[students.models.validate_file_size])),
            ],
        ),
    ]
