# Generated by Django 5.2.7 on 2025-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.URLField(default='pic'),
        ),
    ]
